Layout/EndAlignment:
  Description: 'Align ends correctly.'
  Enabled: false

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  Enabled: false

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  Enabled: true
  Max: 20

Naming/FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: false
